### ISSUE TITLE
Whether updates or patch should be used for changes to insurance information

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/scheduling#47]
Incorporating coverage information into the workflow and when updating information as described [here](https://github.com/argonautproject/scheduling/wiki/Operations#patient-loginregistration) need to decide which option is best:

1. defer to future scope
1. use update as written
1. use [patch](http://build.fhir.org/http.html#patch) interaction

**Comment by cooperthompson** [comment]
In general, I've always struggled to understand when EHR systems would ever actually truly respect an update interaction, PATCH is technically probably the "true" solution.  However...

That said, Coverage doesn't have many of the "hard" elements that make update really challenging (like Address).  The only properties with tricky data types when doing an update interaction (CodeableConcept) are type and relationship.  

- Type is hard, because a reg system will never just update a coverage with new type.  We'd error and ask for a new coverage.  But because we'd error, maybe an update is fine, and if a type change is provided we'd just send back an OO.

- Relationship is probably something we'd be willing to let a client update.

So at the end, I think I'm in favor of update.

**Comment by Healthedata1** [comment]
leave as is and see how work in piloting  ( May not be implemented in time  for Jan connectathon though)
